# Site Settings
title: Plugits | invent, !reinvent
email: 
description: An open forum to share and search composable software components.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plugits.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-144278656-1"

# User Settings
username: Plugits
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: plugits
facebook_username: facebook_username
twitter_username: justplugits
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
